version: '3.5'

services:
  rack:
    command: bash -c "bundle exec rake prod_up && bundle exec puma"
    image: 18xx_rack:prod
    environment:
      RACK_ENV: production
      DATABASE_URL: $DATABASE_URL
    volumes:
      - ./public:/18xx/public
      - ./log/rack:/18xx/log/rack

  db:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  nginx:
    build: ./nginx/
    image: nginx:1.17
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./public:/public
      - /etc/18xxgames/ssl:/etc/18xxgames/ssl
    depends_on:
      - rack
